# Generated by Django 4.2.27 on 2025-12-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_servido_alter_detallepedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Servido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
