# Generated by Django 4.2.27 on 2025-12-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Ocultar de la vista de pedidos activos cuando ya fue cerrado en caja'),
        ),
    ]
