# Generated by Django 4.2.27 on 2025-12-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_id'),
        ('pedidos', '0004_pedido_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_extra',
            field=models.BooleanField(default=False, help_text='Marca si el pedido es una venta rápida (sin mesa)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.mesa'),
        ),
    ]
