# Generated by Django 4.2 on 2025-12-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_id'),
        ('pedidos', '0005_pedido_es_extra_alter_pedido_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='es_extra',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.mesa'),
        ),
    ]
