# Generated by Django 4.2.27 on 2025-12-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedidos', '0006_remove_pedido_es_extra_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante dueño de este pedido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.restaurante'),
        ),
    ]
