# Generated by Django 6.0.3 on 2026-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='consumos_inventario',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
