# Generated by Django 4.2 on 2025-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('sopa', models.CharField(blank=True, max_length=200)),
                ('principios', models.TextField(blank=True, help_text='Lista separada por comas')),
                ('proteinas', models.TextField(blank=True, help_text='Lista separada por comas')),
                ('acompanante', models.CharField(blank=True, max_length=200)),
                ('limonada', models.CharField(blank=True, max_length=200)),
                ('precio_sopa', models.DecimalField(decimal_places=2, default=5000, max_digits=8)),
                ('precio_bandeja', models.DecimalField(decimal_places=2, default=12000, max_digits=8)),
                ('precio_completo', models.DecimalField(decimal_places=2, default=13000, max_digits=8)),
            ],
            options={
                'verbose_name': 'Menú diario',
                'verbose_name_plural': 'Menús diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
