# Generated by Django 4.2.27 on 2025-12-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menudiario_alter_categoria_id_alter_producto_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menudiario",
            name="desayuno_principales",
            field=models.TextField(blank=True, help_text="Lista separada por comas (desayuno)"),
        ),
        migrations.AddField(
            model_name="menudiario",
            name="desayuno_bebidas",
            field=models.TextField(blank=True, help_text="Lista separada por comas (desayuno)"),
        ),
        migrations.AddField(
            model_name="menudiario",
            name="desayuno_acompanante",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="menudiario",
            name="precio_desayuno",
            field=models.DecimalField(decimal_places=2, default=8000, max_digits=8),
        ),
    ]
