# Generated by Django 4.2.27 on 2025-12-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menudiario_desayuno"),
    ]

    operations = [
        migrations.AddField(
            model_name="menudiario",
            name="caldos",
            field=models.TextField(blank=True, help_text="Lista separada por comas de caldos"),
        ),
    ]
