# Generated by Django 4.2.27 on 2025-12-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('menu', '0004_menudiario_caldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante al que pertenece la categoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_menu', to='core.restaurante'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
