# Generated by Django 4.2.27 on 2025-12-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('menu', '0005_categoria_restaurante_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudiario',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante al que pertenece el menú', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_diarios', to='core.restaurante'),
        ),
        migrations.AlterField(
            model_name='menudiario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='menudiario',
            unique_together={('restaurante', 'fecha')},
        ),
    ]
