# Generated by Django 6.0.3 on 2026-04-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0003_ingrediente_restaurante'),
        ('menu', '0006_menudiario_restaurante_alter_menudiario_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='menu.producto')),
            ],
            options={
                'verbose_name': 'Receta de producto',
                'verbose_name_plural': 'Recetas de productos',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoOpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_menu', models.CharField(choices=[('corriente', 'Corriente'), ('desayuno', 'Desayuno')], max_length=20)),
                ('categoria_opcion', models.CharField(choices=[('sopa', 'Sopa'), ('principio', 'Principio'), ('proteina', 'Proteína'), ('acompanante', 'Acompañante'), ('principal', 'Principal'), ('bebida', 'Bebida'), ('caldo', 'Caldo')], max_length=20)),
                ('nombre_opcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad consumida por una unidad vendida al elegir esta opción.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_menu', to='inventario.ingrediente')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_menu', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Consumo por opción de menú',
                'verbose_name_plural': 'Consumos por opción de menú',
                'ordering': ['tipo_menu', 'categoria_opcion', 'nombre_opcion', 'ingrediente__nombre'],
                'unique_together': {('restaurante', 'tipo_menu', 'categoria_opcion', 'nombre_opcion', 'ingrediente')},
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad consumida por una unidad vendida del producto.', max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_producto', to='inventario.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='menu.recetaproducto')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'ordering': ['ingrediente__nombre'],
                'unique_together': {('receta', 'ingrediente')},
            },
        ),
    ]
