# Generated by Django 4.2.27 on 2025-12-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cajasesion_factura_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='salidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
