# Generated by Django 4.2.27 on 2025-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_cajasesion_salidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="cajasesion",
            name="entradas_extra",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
