# Generated by Django 4.2.27 on 2025-12-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0004_cajasesion_entradas_extra"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("tipo", models.CharField(choices=[("entrada", "Entrada"), ("salida", "Salida")], max_length=10)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("concepto", models.CharField(max_length=255)),
                ("sesion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimientos", to="caja.cajasesion")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movimientos_caja", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "ordering": ["-fecha"],
            },
        ),
    ]
