# Generated by Django 4.2.27 on 2025-12-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('caja', '0005_movimientocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante al que pertenece esta sesión de caja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja', to='core.restaurante'),
        ),
    ]
