# Generated by Django 5.2.8 on 2025-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField(default=4)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=10)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Terraza, Interior, VIP', max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
    ]
