# Generated by Django 4.2.27 on 2025-12-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mesas', '0002_alter_mesa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante dueño de esta mesa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.restaurante'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('restaurante', 'numero')},
        ),
    ]
