# Generated by Django 4.2.27 on 2025-12-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_alter_ingrediente_id_alter_movimientoinventario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante dueño de este ingrediente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.restaurante'),
        ),
    ]
