# Generated by Django 4.2.27 on 2025-12-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0002_alter_empleado_id_alter_rol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='Restaurante al que pertenece este empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.restaurante'),
        ),
    ]
