# Generated by Django 4.2.27 on 2026-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hora_entrada',
            field=models.TimeField(blank=True, help_text='Hora habitual de inicio de turno', null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_salida',
            field=models.TimeField(blank=True, help_text='Hora habitual de fin de turno', null=True),
        ),
    ]
