# Generated by Django 4.2.27 on 2025-12-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Teléfono principal, Domicilios, WhatsApp', max_length=100)),
                ('numero', models.CharField(max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(blank=True, help_text='Restaurante dueño de este número', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos_negocio', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Teléfono del negocio',
                'verbose_name_plural': 'Teléfonos del negocio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('telefono_secundario', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('tecnologia', 'Tecnología'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(blank=True, help_text='Restaurante dueño de este proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
